// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDeviceInfo() {
  return window['go']['backend']['App']['GetDeviceInfo']();
}

export function GetDevices() {
  return window['go']['backend']['App']['GetDevices']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function Reboot(arg1) {
  return window['go']['backend']['App']['Reboot'](arg1);
}
