// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function FlashPartition(arg1:string,arg2:string):Promise<void>;

export function GetDeviceInfo():Promise<backend.DeviceInfo>;

export function GetDevices():Promise<Array<backend.Device>>;

export function GetFastbootTest():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Reboot(arg1:string):Promise<void>;

export function WipeData():Promise<void>;
