// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FlashPartition(arg1, arg2) {
  return window['go']['backend']['App']['FlashPartition'](arg1, arg2);
}

export function GetDeviceInfo() {
  return window['go']['backend']['App']['GetDeviceInfo']();
}

export function GetDevices() {
  return window['go']['backend']['App']['GetDevices']();
}

export function GetFastbootDevices() {
  return window['go']['backend']['App']['GetFastbootDevices']();
}

export function Greet(arg1) {
  return window['go']['backend']['App']['Greet'](arg1);
}

export function InstallPackage(arg1) {
  return window['go']['backend']['App']['InstallPackage'](arg1);
}

export function Reboot(arg1) {
  return window['go']['backend']['App']['Reboot'](arg1);
}

export function SelectApkFile() {
  return window['go']['backend']['App']['SelectApkFile']();
}

export function SelectImageFile() {
  return window['go']['backend']['App']['SelectImageFile']();
}

export function UninstallPackage(arg1) {
  return window['go']['backend']['App']['UninstallPackage'](arg1);
}

export function WipeData() {
  return window['go']['backend']['App']['WipeData']();
}
